// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/greenlb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"` // Il Leader dice "Sono io, rispondimi"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_greenlb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greenlb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_greenlb_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

type TelemetryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CurrentPowerWatts float32                `protobuf:"fixed32,2,opt,name=current_power_watts,json=currentPowerWatts,proto3" json:"current_power_watts,omitempty"` // Watt
	IsHealthy         bool                   `protobuf:"varint,3,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`                            // true if the worker is ok
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_proto_greenlb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greenlb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_greenlb_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TelemetryResponse) GetCurrentPowerWatts() float32 {
	if x != nil {
		return x.CurrentPowerWatts
	}
	return 0
}

func (x *TelemetryResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

// === Election messages ===
type ElectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   int32                  `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"` // Nel Bully, l'ID (es. numero porta o IP) determina chi vince
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionRequest) Reset() {
	*x = ElectionRequest{}
	mi := &file_proto_greenlb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionRequest) ProtoMessage() {}

func (x *ElectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greenlb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionRequest.ProtoReflect.Descriptor instead.
func (*ElectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_greenlb_proto_rawDescGZIP(), []int{2}
}

func (x *ElectionRequest) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

type ElectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepDown      bool                   `protobuf:"varint,1,opt,name=step_down,json=stepDown,proto3" json:"step_down,omitempty"` // Se true, il nodo che ha ricevuto la richiesta ha un ID maggiore e blocca il candidato
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionResponse) Reset() {
	*x = ElectionResponse{}
	mi := &file_proto_greenlb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionResponse) ProtoMessage() {}

func (x *ElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greenlb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionResponse.ProtoReflect.Descriptor instead.
func (*ElectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_greenlb_proto_rawDescGZIP(), []int{3}
}

func (x *ElectionResponse) GetStepDown() bool {
	if x != nil {
		return x.StepDown
	}
	return false
}

type CoordinatorAnnouncement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      int32                  `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"` // Indirizzo gRPC del nuovo leader
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorAnnouncement) Reset() {
	*x = CoordinatorAnnouncement{}
	mi := &file_proto_greenlb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorAnnouncement) ProtoMessage() {}

func (x *CoordinatorAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greenlb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorAnnouncement.ProtoReflect.Descriptor instead.
func (*CoordinatorAnnouncement) Descriptor() ([]byte, []int) {
	return file_proto_greenlb_proto_rawDescGZIP(), []int{4}
}

func (x *CoordinatorAnnouncement) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *CoordinatorAnnouncement) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

// === Synchronization messages ===
type StateUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID del leader che invia l'update: permette al follower di scartare
	// messaggi arrivati in ritardo da un leader ormai deposto (vedi PDF, Q4).
	LeaderId int32 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// Il Leader invia l'intera mappa dei worker ai Follower
	Workers       map[string]*WorkerData `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdateRequest) Reset() {
	*x = StateUpdateRequest{}
	mi := &file_proto_greenlb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdateRequest) ProtoMessage() {}

func (x *StateUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greenlb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdateRequest.ProtoReflect.Descriptor instead.
func (*StateUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_greenlb_proto_rawDescGZIP(), []int{5}
}

func (x *StateUpdateRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *StateUpdateRequest) GetWorkers() map[string]*WorkerData {
	if x != nil {
		return x.Workers
	}
	return nil
}

type WorkerData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PowerWatts      float32                `protobuf:"fixed32,2,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	CarbonIntensity float32                `protobuf:"fixed32,3,opt,name=carbon_intensity,json=carbonIntensity,proto3" json:"carbon_intensity,omitempty"`
	IsActive        bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerData) Reset() {
	*x = WorkerData{}
	mi := &file_proto_greenlb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerData) ProtoMessage() {}

func (x *WorkerData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greenlb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerData.ProtoReflect.Descriptor instead.
func (*WorkerData) Descriptor() ([]byte, []int) {
	return file_proto_greenlb_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WorkerData) GetPowerWatts() float32 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

func (x *WorkerData) GetCarbonIntensity() float32 {
	if x != nil {
		return x.CarbonIntensity
	}
	return 0
}

func (x *WorkerData) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_greenlb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greenlb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_greenlb_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_greenlb_proto protoreflect.FileDescriptor

const file_proto_greenlb_proto_rawDesc = "" +
	"\n" +
	"\x13proto/greenlb.proto\"*\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\"\x7f\n" +
	"\x11TelemetryResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12.\n" +
	"\x13current_power_watts\x18\x02 \x01(\x02R\x11currentPowerWatts\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x03 \x01(\bR\tisHealthy\"4\n" +
	"\x0fElectionRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\x05R\vcandidateId\"/\n" +
	"\x10ElectionResponse\x12\x1b\n" +
	"\tstep_down\x18\x01 \x01(\bR\bstepDown\"]\n" +
	"\x17CoordinatorAnnouncement\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x05R\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddress\"\xb6\x01\n" +
	"\x12StateUpdateRequest\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\x12:\n" +
	"\aworkers\x18\x01 \x03(\v2 .StateUpdateRequest.WorkersEntryR\aworkers\x1aG\n" +
	"\fWorkersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.WorkerDataR\x05value:\x028\x01\"\x8f\x01\n" +
	"\n" +
	"WorkerData\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vpower_watts\x18\x02 \x01(\x02R\n" +
	"powerWatts\x12)\n" +
	"\x10carbon_intensity\x18\x03 \x01(\x02R\x0fcarbonIntensity\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2>\n" +
	"\rWorkerService\x12-\n" +
	"\tHeartbeat\x12\f.PingRequest\x1a\x12.TelemetryResponse2\xa5\x01\n" +
	"\x0eClusterService\x124\n" +
	"\rStartElection\x12\x10.ElectionRequest\x1a\x11.ElectionResponse\x125\n" +
	"\x13AnnounceCoordinator\x12\x18.CoordinatorAnnouncement\x1a\x04.Ack\x12&\n" +
	"\tSyncState\x12\x13.StateUpdateRequest\x1a\x04.AckB\"Z greenLoadBalancer/internal/pb;pbb\x06proto3"

var (
	file_proto_greenlb_proto_rawDescOnce sync.Once
	file_proto_greenlb_proto_rawDescData []byte
)

func file_proto_greenlb_proto_rawDescGZIP() []byte {
	file_proto_greenlb_proto_rawDescOnce.Do(func() {
		file_proto_greenlb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greenlb_proto_rawDesc), len(file_proto_greenlb_proto_rawDesc)))
	})
	return file_proto_greenlb_proto_rawDescData
}

var file_proto_greenlb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_greenlb_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: PingRequest
	(*TelemetryResponse)(nil),       // 1: TelemetryResponse
	(*ElectionRequest)(nil),         // 2: ElectionRequest
	(*ElectionResponse)(nil),        // 3: ElectionResponse
	(*CoordinatorAnnouncement)(nil), // 4: CoordinatorAnnouncement
	(*StateUpdateRequest)(nil),      // 5: StateUpdateRequest
	(*WorkerData)(nil),              // 6: WorkerData
	(*Ack)(nil),                     // 7: Ack
	nil,                             // 8: StateUpdateRequest.WorkersEntry
}
var file_proto_greenlb_proto_depIdxs = []int32{
	8, // 0: StateUpdateRequest.workers:type_name -> StateUpdateRequest.WorkersEntry
	6, // 1: StateUpdateRequest.WorkersEntry.value:type_name -> WorkerData
	0, // 2: WorkerService.Heartbeat:input_type -> PingRequest
	2, // 3: ClusterService.StartElection:input_type -> ElectionRequest
	4, // 4: ClusterService.AnnounceCoordinator:input_type -> CoordinatorAnnouncement
	5, // 5: ClusterService.SyncState:input_type -> StateUpdateRequest
	1, // 6: WorkerService.Heartbeat:output_type -> TelemetryResponse
	3, // 7: ClusterService.StartElection:output_type -> ElectionResponse
	7, // 8: ClusterService.AnnounceCoordinator:output_type -> Ack
	7, // 9: ClusterService.SyncState:output_type -> Ack
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_greenlb_proto_init() }
func file_proto_greenlb_proto_init() {
	if File_proto_greenlb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greenlb_proto_rawDesc), len(file_proto_greenlb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_greenlb_proto_goTypes,
		DependencyIndexes: file_proto_greenlb_proto_depIdxs,
		MessageInfos:      file_proto_greenlb_proto_msgTypes,
	}.Build()
	File_proto_greenlb_proto = out.File
	file_proto_greenlb_proto_goTypes = nil
	file_proto_greenlb_proto_depIdxs = nil
}
